//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.serviAseSMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://ws_sms.msg-server.net/entrypoint")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idreferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string countrycode {
            get {
                return this.countrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countrycodeField, value) != true)) {
                    this.countrycodeField = value;
                    this.RaisePropertyChanged("countrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Message", EmitDefaultValue=false, Order=2)]
        public string MessageMember {
            get {
                return this.MessageMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageMemberField, value) != true)) {
                    this.MessageMemberField = value;
                    this.RaisePropertyChanged("MessageMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string idreference {
            get {
                return this.idreferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.idreferenceField, value) != true)) {
                    this.idreferenceField = value;
                    this.RaisePropertyChanged("idreference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSResponse", Namespace="http://ws_sms.msg-server.net/entrypoint")]
    [System.SerializableAttribute()]
    public partial class SMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errordesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errordes {
            get {
                return this.errordesField;
            }
            set {
                if ((object.ReferenceEquals(this.errordesField, value) != true)) {
                    this.errordesField = value;
                    this.RaisePropertyChanged("errordes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint", ConfigurationName="serviAseSMS.WSMSGSoap")]
    public interface WSMSGSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PingResult del espacio de nombres http://ws_sms.msg-server.net/entrypoint no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/Ping", ReplyAction="*")]
        WindowsFormsApp1.serviAseSMS.PingResponse Ping(WindowsFormsApp1.serviAseSMS.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.PingResponse> PingAsync(WindowsFormsApp1.serviAseSMS.PingRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://ws_sms.msg-server.net/entrypoint no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/CheckStatus", ReplyAction="*")]
        WindowsFormsApp1.serviAseSMS.CheckStatusResponse CheckStatus(WindowsFormsApp1.serviAseSMS.CheckStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/CheckStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.CheckStatusResponse> CheckStatusAsync(WindowsFormsApp1.serviAseSMS.CheckStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://ws_sms.msg-server.net/entrypoint no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/SendMessage", ReplyAction="*")]
        WindowsFormsApp1.serviAseSMS.SendMessageResponse SendMessage(WindowsFormsApp1.serviAseSMS.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.SendMessageResponse> SendMessageAsync(WindowsFormsApp1.serviAseSMS.SendMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public WindowsFormsApp1.serviAseSMS.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(WindowsFormsApp1.serviAseSMS.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody {
        
        public PingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public WindowsFormsApp1.serviAseSMS.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(WindowsFormsApp1.serviAseSMS.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingResult;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(string PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStatus", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public WindowsFormsApp1.serviAseSMS.CheckStatusRequestBody Body;
        
        public CheckStatusRequest() {
        }
        
        public CheckStatusRequest(WindowsFormsApp1.serviAseSMS.CheckStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class CheckStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public CheckStatusRequestBody() {
        }
        
        public CheckStatusRequestBody(string username, string password, int id) {
            this.username = username;
            this.password = password;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStatusResponse", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public WindowsFormsApp1.serviAseSMS.CheckStatusResponseBody Body;
        
        public CheckStatusResponse() {
        }
        
        public CheckStatusResponse(WindowsFormsApp1.serviAseSMS.CheckStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class CheckStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckStatusResult;
        
        public CheckStatusResponseBody() {
        }
        
        public CheckStatusResponseBody(string CheckStatusResult) {
            this.CheckStatusResult = CheckStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public WindowsFormsApp1.serviAseSMS.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(WindowsFormsApp1.serviAseSMS.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApp1.serviAseSMS.Message message;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string username, string password, WindowsFormsApp1.serviAseSMS.Message message) {
            this.username = username;
            this.password = password;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public WindowsFormsApp1.serviAseSMS.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(WindowsFormsApp1.serviAseSMS.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.serviAseSMS.SMSResponse SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(WindowsFormsApp1.serviAseSMS.SMSResponse SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSMSGSoapChannel : WindowsFormsApp1.serviAseSMS.WSMSGSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMSGSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.serviAseSMS.WSMSGSoap>, WindowsFormsApp1.serviAseSMS.WSMSGSoap {
        
        public WSMSGSoapClient() {
        }
        
        public WSMSGSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMSGSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMSGSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMSGSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.serviAseSMS.PingResponse WindowsFormsApp1.serviAseSMS.WSMSGSoap.Ping(WindowsFormsApp1.serviAseSMS.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping() {
            WindowsFormsApp1.serviAseSMS.PingRequest inValue = new WindowsFormsApp1.serviAseSMS.PingRequest();
            inValue.Body = new WindowsFormsApp1.serviAseSMS.PingRequestBody();
            WindowsFormsApp1.serviAseSMS.PingResponse retVal = ((WindowsFormsApp1.serviAseSMS.WSMSGSoap)(this)).Ping(inValue);
            return retVal.Body.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.PingResponse> WindowsFormsApp1.serviAseSMS.WSMSGSoap.PingAsync(WindowsFormsApp1.serviAseSMS.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.PingResponse> PingAsync() {
            WindowsFormsApp1.serviAseSMS.PingRequest inValue = new WindowsFormsApp1.serviAseSMS.PingRequest();
            inValue.Body = new WindowsFormsApp1.serviAseSMS.PingRequestBody();
            return ((WindowsFormsApp1.serviAseSMS.WSMSGSoap)(this)).PingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.serviAseSMS.CheckStatusResponse WindowsFormsApp1.serviAseSMS.WSMSGSoap.CheckStatus(WindowsFormsApp1.serviAseSMS.CheckStatusRequest request) {
            return base.Channel.CheckStatus(request);
        }
        
        public string CheckStatus(string username, string password, int id) {
            WindowsFormsApp1.serviAseSMS.CheckStatusRequest inValue = new WindowsFormsApp1.serviAseSMS.CheckStatusRequest();
            inValue.Body = new WindowsFormsApp1.serviAseSMS.CheckStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.id = id;
            WindowsFormsApp1.serviAseSMS.CheckStatusResponse retVal = ((WindowsFormsApp1.serviAseSMS.WSMSGSoap)(this)).CheckStatus(inValue);
            return retVal.Body.CheckStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.CheckStatusResponse> WindowsFormsApp1.serviAseSMS.WSMSGSoap.CheckStatusAsync(WindowsFormsApp1.serviAseSMS.CheckStatusRequest request) {
            return base.Channel.CheckStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.CheckStatusResponse> CheckStatusAsync(string username, string password, int id) {
            WindowsFormsApp1.serviAseSMS.CheckStatusRequest inValue = new WindowsFormsApp1.serviAseSMS.CheckStatusRequest();
            inValue.Body = new WindowsFormsApp1.serviAseSMS.CheckStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.id = id;
            return ((WindowsFormsApp1.serviAseSMS.WSMSGSoap)(this)).CheckStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.serviAseSMS.SendMessageResponse WindowsFormsApp1.serviAseSMS.WSMSGSoap.SendMessage(WindowsFormsApp1.serviAseSMS.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public WindowsFormsApp1.serviAseSMS.SMSResponse SendMessage(string username, string password, WindowsFormsApp1.serviAseSMS.Message message) {
            WindowsFormsApp1.serviAseSMS.SendMessageRequest inValue = new WindowsFormsApp1.serviAseSMS.SendMessageRequest();
            inValue.Body = new WindowsFormsApp1.serviAseSMS.SendMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.message = message;
            WindowsFormsApp1.serviAseSMS.SendMessageResponse retVal = ((WindowsFormsApp1.serviAseSMS.WSMSGSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.SendMessageResponse> WindowsFormsApp1.serviAseSMS.WSMSGSoap.SendMessageAsync(WindowsFormsApp1.serviAseSMS.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.serviAseSMS.SendMessageResponse> SendMessageAsync(string username, string password, WindowsFormsApp1.serviAseSMS.Message message) {
            WindowsFormsApp1.serviAseSMS.SendMessageRequest inValue = new WindowsFormsApp1.serviAseSMS.SendMessageRequest();
            inValue.Body = new WindowsFormsApp1.serviAseSMS.SendMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.message = message;
            return ((WindowsFormsApp1.serviAseSMS.WSMSGSoap)(this)).SendMessageAsync(inValue);
        }
    }
}
