//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSCobros.wsSMSC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://ws_sms.msg-server.net/entrypoint")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idreferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string countrycode {
            get {
                return this.countrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countrycodeField, value) != true)) {
                    this.countrycodeField = value;
                    this.RaisePropertyChanged("countrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Message", EmitDefaultValue=false, Order=2)]
        public string MessageMember {
            get {
                return this.MessageMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageMemberField, value) != true)) {
                    this.MessageMemberField = value;
                    this.RaisePropertyChanged("MessageMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string idreference {
            get {
                return this.idreferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.idreferenceField, value) != true)) {
                    this.idreferenceField = value;
                    this.RaisePropertyChanged("idreference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSResponse", Namespace="http://ws_sms.msg-server.net/entrypoint")]
    [System.SerializableAttribute()]
    public partial class SMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errordesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errordes {
            get {
                return this.errordesField;
            }
            set {
                if ((object.ReferenceEquals(this.errordesField, value) != true)) {
                    this.errordesField = value;
                    this.RaisePropertyChanged("errordes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint", ConfigurationName="wsSMSC.WSMSGSoap")]
    public interface WSMSGSoap {
        
        // CODEGEN: Generating message contract since element name PingResult from namespace http://ws_sms.msg-server.net/entrypoint is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/Ping", ReplyAction="*")]
        SMSCobros.wsSMSC.PingResponse Ping(SMSCobros.wsSMSC.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCobros.wsSMSC.PingResponse> PingAsync(SMSCobros.wsSMSC.PingRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://ws_sms.msg-server.net/entrypoint is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/CheckStatus", ReplyAction="*")]
        SMSCobros.wsSMSC.CheckStatusResponse CheckStatus(SMSCobros.wsSMSC.CheckStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/CheckStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCobros.wsSMSC.CheckStatusResponse> CheckStatusAsync(SMSCobros.wsSMSC.CheckStatusRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://ws_sms.msg-server.net/entrypoint is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/SendMessage", ReplyAction="*")]
        SMSCobros.wsSMSC.SendMessageResponse SendMessage(SMSCobros.wsSMSC.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws_sms.msg-server.net/entrypoint/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<SMSCobros.wsSMSC.SendMessageResponse> SendMessageAsync(SMSCobros.wsSMSC.SendMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public SMSCobros.wsSMSC.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(SMSCobros.wsSMSC.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody {
        
        public PingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public SMSCobros.wsSMSC.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(SMSCobros.wsSMSC.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingResult;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(string PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStatus", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public SMSCobros.wsSMSC.CheckStatusRequestBody Body;
        
        public CheckStatusRequest() {
        }
        
        public CheckStatusRequest(SMSCobros.wsSMSC.CheckStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class CheckStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public CheckStatusRequestBody() {
        }
        
        public CheckStatusRequestBody(string username, string password, int id) {
            this.username = username;
            this.password = password;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStatusResponse", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public SMSCobros.wsSMSC.CheckStatusResponseBody Body;
        
        public CheckStatusResponse() {
        }
        
        public CheckStatusResponse(SMSCobros.wsSMSC.CheckStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class CheckStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckStatusResult;
        
        public CheckStatusResponseBody() {
        }
        
        public CheckStatusResponseBody(string CheckStatusResult) {
            this.CheckStatusResult = CheckStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public SMSCobros.wsSMSC.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(SMSCobros.wsSMSC.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SMSCobros.wsSMSC.Message message;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string username, string password, SMSCobros.wsSMSC.Message message) {
            this.username = username;
            this.password = password;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://ws_sms.msg-server.net/entrypoint", Order=0)]
        public SMSCobros.wsSMSC.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(SMSCobros.wsSMSC.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_sms.msg-server.net/entrypoint")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SMSCobros.wsSMSC.SMSResponse SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(SMSCobros.wsSMSC.SMSResponse SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSMSGSoapChannel : SMSCobros.wsSMSC.WSMSGSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMSGSoapClient : System.ServiceModel.ClientBase<SMSCobros.wsSMSC.WSMSGSoap>, SMSCobros.wsSMSC.WSMSGSoap {
        
        public WSMSGSoapClient() {
        }
        
        public WSMSGSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMSGSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMSGSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMSGSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSCobros.wsSMSC.PingResponse SMSCobros.wsSMSC.WSMSGSoap.Ping(SMSCobros.wsSMSC.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping() {
            SMSCobros.wsSMSC.PingRequest inValue = new SMSCobros.wsSMSC.PingRequest();
            inValue.Body = new SMSCobros.wsSMSC.PingRequestBody();
            SMSCobros.wsSMSC.PingResponse retVal = ((SMSCobros.wsSMSC.WSMSGSoap)(this)).Ping(inValue);
            return retVal.Body.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCobros.wsSMSC.PingResponse> SMSCobros.wsSMSC.WSMSGSoap.PingAsync(SMSCobros.wsSMSC.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCobros.wsSMSC.PingResponse> PingAsync() {
            SMSCobros.wsSMSC.PingRequest inValue = new SMSCobros.wsSMSC.PingRequest();
            inValue.Body = new SMSCobros.wsSMSC.PingRequestBody();
            return ((SMSCobros.wsSMSC.WSMSGSoap)(this)).PingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSCobros.wsSMSC.CheckStatusResponse SMSCobros.wsSMSC.WSMSGSoap.CheckStatus(SMSCobros.wsSMSC.CheckStatusRequest request) {
            return base.Channel.CheckStatus(request);
        }
        
        public string CheckStatus(string username, string password, int id) {
            SMSCobros.wsSMSC.CheckStatusRequest inValue = new SMSCobros.wsSMSC.CheckStatusRequest();
            inValue.Body = new SMSCobros.wsSMSC.CheckStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.id = id;
            SMSCobros.wsSMSC.CheckStatusResponse retVal = ((SMSCobros.wsSMSC.WSMSGSoap)(this)).CheckStatus(inValue);
            return retVal.Body.CheckStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCobros.wsSMSC.CheckStatusResponse> SMSCobros.wsSMSC.WSMSGSoap.CheckStatusAsync(SMSCobros.wsSMSC.CheckStatusRequest request) {
            return base.Channel.CheckStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCobros.wsSMSC.CheckStatusResponse> CheckStatusAsync(string username, string password, int id) {
            SMSCobros.wsSMSC.CheckStatusRequest inValue = new SMSCobros.wsSMSC.CheckStatusRequest();
            inValue.Body = new SMSCobros.wsSMSC.CheckStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.id = id;
            return ((SMSCobros.wsSMSC.WSMSGSoap)(this)).CheckStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSCobros.wsSMSC.SendMessageResponse SMSCobros.wsSMSC.WSMSGSoap.SendMessage(SMSCobros.wsSMSC.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public SMSCobros.wsSMSC.SMSResponse SendMessage(string username, string password, SMSCobros.wsSMSC.Message message) {
            SMSCobros.wsSMSC.SendMessageRequest inValue = new SMSCobros.wsSMSC.SendMessageRequest();
            inValue.Body = new SMSCobros.wsSMSC.SendMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.message = message;
            SMSCobros.wsSMSC.SendMessageResponse retVal = ((SMSCobros.wsSMSC.WSMSGSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSCobros.wsSMSC.SendMessageResponse> SMSCobros.wsSMSC.WSMSGSoap.SendMessageAsync(SMSCobros.wsSMSC.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSCobros.wsSMSC.SendMessageResponse> SendMessageAsync(string username, string password, SMSCobros.wsSMSC.Message message) {
            SMSCobros.wsSMSC.SendMessageRequest inValue = new SMSCobros.wsSMSC.SendMessageRequest();
            inValue.Body = new SMSCobros.wsSMSC.SendMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.message = message;
            return ((SMSCobros.wsSMSC.WSMSGSoap)(this)).SendMessageAsync(inValue);
        }
    }
}
