//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNoti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int IdParametro { get; set; }
        public string IdKey { get; set; }
        public string DetalleParametro { get; set; }
        public string Valor { get; set; }
        public int Activo { get; set; }
    }
}
