//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_MENSAJES_SMS_BIT
    {
        public decimal NUM_MENSAJE { get; set; }
        public string NUM_TELEFONO { get; set; }
        public string MENSAJE { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string IND_ESTADO { get; set; }
        public string COD_MODULO { get; set; }
        public string DETALLE { get; set; }
    }
}
